version: "3"
services:
  mysql:
    build: .
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql_volume:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
    env_file:
      - config/.env
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_volume: